--
-- Contact Submissions Table
-- Used to store contact form submissions from the website
--
CREATE TABLE IF NOT EXISTS contact_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'replied', 'archived'))
);

-- Enable RLS
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;

-- Policies for Contact Submissions
-- Allow public to insert (anyone can submit contact form)
CREATE POLICY "Enable insert for public" ON contact_submissions
    FOR INSERT
    TO public
    WITH CHECK (true);

-- Allow admins (service_role) to view and update all submissions
CREATE POLICY "Allow service_role full access" ON contact_submissions
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Add trigger for updated_at
CREATE TRIGGER update_contact_submissions_updated_at
    BEFORE UPDATE ON contact_submissions
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
