-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--
-- 1. Admins Table
-- Used for authentication in /src/lib/auth.ts
--
CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, -- Stores bcrypt hash
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Policies for Admins
-- Only allow service_role (server-side) to access this table fully.
-- This prevents any client-side exposure.
CREATE POLICY "Allow service_role full access" ON admins
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);


--
-- 2. Bookings Table
-- Used in /src/app/api/bookings/create/route.ts
--
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    service TEXT NOT NULL,
    date DATE NOT NULL,
    time TEXT NOT NULL,
    message TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled'))
);

-- Enable RLS
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Policies for Bookings
-- Allow public to insert (anyone can book)
CREATE POLICY "Enable insert for public" ON bookings
    FOR INSERT
    TO public
    WITH CHECK (true);

-- Allow admins (service_role) to view and update all bookings
CREATE POLICY "Allow service_role full access" ON bookings
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);


--
-- 3. Blogs Table
-- Used in /src/app/api/blogs/route.ts
--
CREATE TABLE IF NOT EXISTS blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT NOT NULL,
    featured_image TEXT,
    category TEXT NOT NULL,
    tags TEXT[],
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    author TEXT NOT NULL,
    published_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;

-- Policies for Blogs
-- Allow public to view published blogs
CREATE POLICY "Enable read access for public" ON blogs
    FOR SELECT
    TO public
    USING (status = 'published');

-- Allow admins (service_role) full access
CREATE POLICY "Allow service_role full access" ON blogs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

--
-- 4. Storage Bucket for Images
-- Used in /src/app/api/upload/route.ts ('wellness' bucket)
--
INSERT INTO storage.buckets (id, name, public)
VALUES ('wellness', 'wellness', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Allow public read access to 'wellness' bucket
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
TO public
USING ( bucket_id = 'wellness' );

-- Allow authenticated uploads (service_role mostly, but could be specific users if needed)
-- Since uploads happen via API route using service_role, this is implicitly handled if using service_role client.
-- But if using anon key for some future client-side upload:
CREATE POLICY "Authenticated Upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'wellness' );


--
-- Optional: Helper trigger for updated_at
--
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_admins_updated_at
    BEFORE UPDATE ON admins
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_bookings_updated_at
    BEFORE UPDATE ON bookings
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_blogs_updated_at
    BEFORE UPDATE ON blogs
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
